---
env:
  CC: /bin/false
workspaces:
  .:
    icon: js
    label: bazel-lib
  e2e/bzlmod:
    icon: bazel
    tasks:
      buildifier:
        without: true
  e2e/copy_to_directory:
    icon: bazel
    tasks:
      buildifier:
        without: true
tasks:
  buildifier:
  test:
